### ISSUE TITLE
Tip from a Thirdparty

### ISSUE THREAD

**Issue by kingthorin** [zaproxy/zap-swag#1]
I recently had someone point out that the "Doing Bad Things for the RIGHT reasons" stickers don't actually mention ZAP.

https://github.com/zaproxy/zap-swag/blob/master/stickers/Sticker_Doing_bad_things_bumper.png
https://github.com/zaproxy/zap-swag/blob/master/stickers/Sticker_Doing_bad_things_round.png

While this isn't an issue for the core team, or contributors, etc. the logo is pretty recognizable within the community. However, it might be a missed marketing opportunity given that these stickers adorn laptops etc that go to all kinds of conferences etc.

Food for thought.

**Comment by psiinon** [comment]
Yeah, I kind of like the fact they dont mention ZAP, but I can also see that maybe they should ;)

**Comment by kingthorin** [comment]
I don't think this needs to remain open.
